open_weather_map_api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
google_calendar_id = 'xxxxxxxxxxxxxxxxxxxx@group.calendar.google.com'
google_api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
wordnik_api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
forecastio_api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
